/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Pdf2imgImport } from './routes/pdf2img'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Pdf2imgRoute = Pdf2imgImport.update({
  id: '/pdf2img',
  path: '/pdf2img',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pdf2img': {
      id: '/pdf2img'
      path: '/pdf2img'
      fullPath: '/pdf2img'
      preLoaderRoute: typeof Pdf2imgImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pdf2img': typeof Pdf2imgRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pdf2img': typeof Pdf2imgRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pdf2img': typeof Pdf2imgRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pdf2img'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pdf2img'
  id: '__root__' | '/' | '/pdf2img'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Pdf2imgRoute: typeof Pdf2imgRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Pdf2imgRoute: Pdf2imgRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pdf2img"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pdf2img": {
      "filePath": "pdf2img.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
